
[toolchain]
anchor_version = "0.29.0"


[features]
seeds = false
skip-lint = false

[programs.localnet]
solami_rewards = "AeDRnzQh9VJswa71LWQrcP1R1AhT2bdtKmkjsCvyUzq6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/apple/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"